config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users, path: "users"
  devise_for :admins, path: "admins"

  namespace :admin do
    resources :events
  end

  resources :events, only: [:show] do
    resources :participations, only: [:create]
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user, presence: true
  validates :event, presence: true
  validates :content, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  after_update :notify

  belongs_to :admin
  has_many :participations
  has_many :users, through: :participations
  has_many :comments

  validates :name, presence: true
  validates :description, presence: true
  validates :start_at, presence: true
  validates :slots,
    numericality: { greater_than: 0, only_integer: true },
    presence: true
  validates :city, presence: true
  validates :country_id, presence: true
  validates :distance,
    numericality: { greater_than: 0, only_integer: true },
    presence: true
  validate :participations_count

  scope :upcoming, -> { where("start_at >= ?", Date.current) }

  def participations_count
    errors.add(:tags, "too much participations") if participations.size >= slots
  end

  def notify
    users.each do |user|
      EventMailFactory.build(self, user)
    end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  AGE_CATEGORIES = %w( G16 G20 G30 G40 G50 G60 G70 ).freeze

  belongs_to :user
  belongs_to :event

  validates :user, presence: true, uniqueness: { scope: :event }
  validates :event, presence: true
  validates :age_category, presence: true,
    inclusion: { in: AGE_CATEGORIES,
      message: "is not a valid age age_category" }
  validates :start_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :participations
  has_many :events, through: :participations
  has_many :comments

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthdate, presence: true
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  before_action :set_event, only: [:edit, :update, :destroy]

  def index
    @events = current_admin.events.decorate
  end

  def new
    @event = current_admin.events.build
  end

  def create
    @event = current_admin.events.build(event_params)

    if @event.save
      redirect_to admin_events_path, notice: "Event was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to admin_events_path, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy

    if @event.destroyed?
      redirect_to admin_events_path, notice: "Event was successfully destroyed."
    else
      redirect_to admin_events_path, alert: "Something went wrong."
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :country_id, :city,
      :slots, :start_at, :distance)
  end

  def set_event
    @event = current_admin.events.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:first_name, :last_name, :birthdate])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    event = Event.find(params[:event_id])
    @comment = current_user.comments.build(comment_params.merge(event: event))

    if @comment.save
      redirect_to event_path(event)
    else
      redirect_to event_path(event), alert: "Something went wrong"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id]).decorate
    @comment = Comment.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.upcoming.decorate
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :authenticate_user!

  def create
    event = Event.find(params[:event_id])
    builder = ParticipationBuilder.new
    builder.add_event(event)
    builder.add_user(current_user)
    builder.configure

    if builder.participation.save
      redirect_to event_path(event),
        notice: "You successfully joined to the event"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @user = UserFacade.new(user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/events/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading
        %h3.panel-title New event
      .panel-body
        = simple_form_for [:admin, @event] do |f|
          = f.input :name
          = f.input :description
          .row
            .col-md-6
              = f.input :start_at
          .row
            .col-md-6
              = f.input :distance
            .col-md-6
              = f.input :slots
          .row
            .col-md-6
              = f.input :country_id, priority: ["Poland"]
            .col-md-6
              = f.input :city
          = f.button :submit, class: "btn-primary"

app/views/admin/events/edit.html.haml
= render "form"

app/views/admin/events/index.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading
        %h3.panel-title Events
      .panel-body
        %table.table
          %thead
            %tr
              %th Name
              %th Distance
              %th Location
              %th Start at
              %th.buttons
          %tbody
            - @events.each do |event|
              %tr
                %td=event.name
                %td=event.location
                %td=event.formatted_distance
                %td=event.formatted_start_at
                %td
                  = link_to "Edit", edit_admin_event_path(event)
                  = link_to "Destroy", admin_event_path(event),
                    method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/events/new.html.haml
= render "form"

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/events/show.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading
        %h3.panel-title=@event.name
      .panel-body
        %p
          %i.glyphicon.glyphicon-calendar="\t#{@event.formatted_start_at}"
          %br
          %i.glyphicon.glyphicon-home="\t#{@event.location}"
          %br
          %i.glyphicon.glyphicon-user="\t#{@event.slots}"
          %br
          %i.glyphicon.glyphicon-cog="\t#{@event.formatted_distance}"
        %p=@event.description

        - if current_user.present?
          =link_to "Join", event_participations_path(@event), method: :post

        %hr/
        %h5 Users:
        - i = ArrayIterator.new(@event.users.decorate)
        - while i.has_next?
          = i.next_item.full_name

    - if @event.comments.exists?
      .panel.panel-default
        .panel-heading
          %h3.panel-title Comments
        .panel-body
          - @event.comments.decorate.each do |comment|
            %small="#{comment.user.email} | #{comment.formatted_created_at}"
            %br/
            =comment.content
            %hr/

    - if current_user
      .panel.panel-default
        .panel-heading
          %h3.panel-title Add comment
        .panel-body
          = simple_form_for [@event, @comment] do |f|
            = f.input :content
            = f.button :submit

app/views/home/index.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading
        %h3.panel-title Events
      .panel-body
        %table.table
          %thead
            %tr
              %th Name
              %th Distance
              %th Location
              %th Start at
              %th.buttons
          %tbody
            - @events.each do |event|
              %tr
                %td=event.name
                %td=event.location
                %td=event.formatted_distance
                %td=event.formatted_start_at
                %td
                  = link_to "Show", event_path(event)

app/views/layouts/_user_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Run Events
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if !current_user.present?
          %li
            =link_to "Sign up", new_user_registration_path
          %li
            =link_to "Sign in", new_user_session_path
        - else
          %li
            =link_to current_user.email, edit_user_registration_path(current_user)
          %li
            =link_to "Sign out", destroy_user_session_path,
              method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RunEvents
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/user_navbar"
    = yield

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading
        %h3.panel-title=@user.user.email
      .panel-body
        %h5 User events
        - @user.recent_events.each do |event|
          = event.name
          %br/

        %hr/

        %h5 User recent comments
        - @user.recent_comments.each do |comment|
          = comment.content
          %br/